=== cfd-learner/labogrid/src/main/schema/labogrid-conf-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:annotation>
		<xs:documentation xml:lang="en">
			This file contains the description of a configuration 
			file of parameters for a LaBoGrid experiment.
		</xs:documentation>
	</xs:annotation>
	
	
	
	<!-- Global types -->
	<xs:simpleType name="boolean">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="SolidFileType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ascii"/>
			<xs:enumeration value="compressed-ascii"/>
			<xs:enumeration value="bin"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	
	<!-- LBConfiguration type declarations -->
	<xs:complexType name="LatticeType">
		<xs:attribute name="size" type="xs:string" use="required"/>
		<xs:attribute name="class" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="SolidType">
		<xs:attribute name="fileId" type="xs:string" use="required"/>
		<xs:attribute name="type" type="SolidFileType" use="required"/>
		<xs:attribute name="class" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="SubLatticesType">
		<xs:attribute name="minSubLatticesCount" type="xs:integer" use="required"/>
		<xs:attribute name="generatorClass" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="LBConfType">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="Lattice" type="LatticeType"/>
			<xs:element name="Solid" type="SolidType"/>
			<xs:element name="SubLattices" type="SubLatticesType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	
		
	<!-- Experiment type declarations -->
	<xs:complexType name="InOutType">
		<xs:attribute name="clientClass" type="xs:string" use="required"/>
		<xs:attribute name="parameters" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="ExperimentType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="SimulationSequence" type="SimulationSequenceType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="SimulationType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="Input" type="InOutType"/>
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:element name="Output" type="InOutType"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="startingIteration" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="iterationsCount" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="processingChain" type="xs:string" use="required"/>
		<xs:attribute name="lbConfiguration" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="NextSimulationType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:element name="Input" type="InOutType"/>
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:element name="Output" type="InOutType"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="iterationsCount" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="processingChain" type="xs:string" use="required"/>
		<xs:attribute name="lbConfiguration" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="SimulationSequenceType">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="Simulation" type="SimulationType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="NextSimulation" type="NextSimulationType"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	
	
	<!-- ProcessingChains type declarations -->
	<xs:complexType name="OperatorType">
		<xs:attribute name="class" type="xs:string" use="required"/>
		<xs:attribute name="parameters" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="LoggerType">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="rate" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="loggerClass" type="xs:string" use="required"/>
		<xs:attribute name="loggerParameters" type="xs:string" use="required"/>
		<xs:attribute name="clientClass" type="xs:string" use="required"/>
		<xs:attribute name="clientParameters" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:group name="ProcChainElement">
		<xs:choice>
			<xs:element name="Operator" type="OperatorType"/>
			<xs:element name="Logger" type="LoggerType"/>
		</xs:choice>
	</xs:group>
	
	<xs:complexType name="ProcChainType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:group ref="ProcChainElement"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>

	
	<!-- LaBoGridMiddleware type declarations -->
	<xs:complexType name="ConfSchedType">
		<xs:attribute name="benchTO" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="reconfTO" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="brokenTO" type="xs:nonNegativeInteger" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="BenchmarkType">
		<xs:attribute name="iterations" type="xs:string"
			use="required" />
		<xs:attribute name="refSizes" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="LoadBalancingType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="Benchmark" type="BenchmarkType" />
		</xs:sequence>
		<xs:attribute name="buildPowerModel" type="boolean"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="FaultToleranceType">
		<xs:attribute name="backupRate" type="xs:nonNegativeInteger"
			use="required" />
		<xs:attribute name="neighborsCount" type="xs:nonNegativeInteger"
			use="required" />
		<xs:attribute name="chunkSize" type="xs:nonNegativeInteger"
			use="required" />
		<xs:attribute name="compressFiles" type="StateFileContentType"
			use="required" />
		<xs:attribute name="replicationEnabled" type="boolean" use="required"/>
	</xs:complexType>

	<xs:complexType name="LBGMiddlewareType">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="Stabilizer" type="StabilizerType" />
			<xs:element name="LoadBalancing" type="LoadBalancingType" />
			<xs:element name="FaultTolerance" type="FaultToleranceType" />
		</xs:sequence>
	</xs:complexType>



	<!-- Configuration file structure -->
	<xs:element name="LaBoGridConfiguration">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="Experiment" type="ExperimentType" />
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<xs:element name="LBConfiguration"
						type="LBConfType" />
				</xs:sequence>
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<xs:element name="ProcessingChain"
						type="ProcChainType" />
				</xs:sequence>
				<xs:element name="LaBoGridMiddleware"
					type="LBGMiddlewareType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	

	<xs:simpleType name="StateFileContentType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="compress"></xs:enumeration>
			<xs:enumeration value="mixed"></xs:enumeration>
			<xs:enumeration value="raw"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>



	<xs:complexType name="StabilizerType">
		<xs:attribute name="timeout" type="xs:nonNegativeInteger"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== cfd-learner/labogrid/src/main/sim-test/conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  LaBoGrid
  %%
  Copyright (C) 2011 LaBoGrid Team
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as
  published by the Free Software Foundation, either version 3 of the 
  License, or (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public 
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/gpl-3.0.html>.
  #L%
  -->

<LaBoGridConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../schema/labogrid-conf-schema.xsd">

	<Experiment>
		<SimulationSequence>
			<Simulation
				iterationsCount="10" lbConfiguration="conf0"
				processingChain="proc0" startingIteration="0">
				<Input clientClass="laboGrid.ioClients.standalone.StandAloneInputClient"
					parameters="src/main/sim-test/ Resource0 50200" />
				<Output clientClass="laboGrid.ioClients.standalone.StandAloneOutputClient"
					parameters="524288 src/main/sim-test/out/ Resource0 50200" />
			</Simulation>
			<NextSimulation
				iterationsCount="10" lbConfiguration="conf0"
				processingChain="proc0">
				<Output clientClass="laboGrid.ioClients.standalone.StandAloneOutputClient"
					parameters="524288 src/main/sim-test/out2/ Resource0 50200" />
			</NextSimulation>
		</SimulationSequence>
		<SimulationSequence>
		<Simulation
			iterationsCount="80"
			lbConfiguration="conf0"
			processingChain="proc1"
			startingIteration="20">
			<Input
				clientClass="laboGrid.ioClients.standalone.StandAloneInputClient"
				parameters="src/main/sim-test/
					Resource0 50200" />
			<Output
				clientClass="laboGrid.ioClients.standalone.StandAloneOutputClient"
				parameters="524288 src/main/sim-test/out/
					Resource0 50200" />
		</Simulation>
	</SimulationSequence>
	</Experiment>

	<LBConfiguration id="conf0">
		<Lattice class="laboGrid.lb.lattice.d3.q19.D3Q19DefaultLattice" size="(44,44,44)" />
		<Solid class="laboGrid.lb.solid.d3.D3SolidBitmap" fileId="MU44.mat.gz" type="compressed-ascii" />
		<SubLattices generatorClass="laboGrid.graphs.model.d3.D3CuboidsGenerator"
			minSubLatticesCount="9" />
	</LBConfiguration>

	<ProcessingChain id="proc0">
		<Operator class="laboGrid.procChain.operators.NonBlockingBorderSender" parameters="" />
		<Operator class="laboGrid.procChain.operators.InPlaceStream"
			parameters="" />
		<Operator class="laboGrid.procChain.operators.BorderFiller" parameters="" />
		<Operator class="laboGrid.procChain.operators.d3.q19.D3Q19PressureOperator"
			parameters="0 1.001 0.999" />
		<Operator class="laboGrid.procChain.operators.d3.q19.D3Q19MRTCollisionOperator"
			parameters="1 0 0 0 20" />
		<Operator class="laboGrid.procChain.operators.WaitBorderSent" parameters="" />
		<Logger id="iter0" rate="1"
			loggerClass="laboGrid.procChain.loggers.IterationLogger"
			loggerParameters=""
			clientClass="laboGrid.procChain.loggers.client.StandAloneLogClient"
			clientParameters="Resource0 50200"/>
		<Logger id="points0" rate="3"
			loggerClass="laboGrid.procChain.loggers.d3.D3PointsLogger"
			loggerParameters="(0,0,0) (10,10,10) (22,22,22)"
			clientClass="laboGrid.procChain.loggers.client.StandAloneLogClient"
			clientParameters="Resource0 50200"/>
		<Logger id="slices0" rate="3"
			loggerClass="laboGrid.procChain.loggers.d3.D3SliceLogger"
			loggerParameters="XY 22"
			clientClass="laboGrid.procChain.loggers.client.StandAloneLogClient"
			clientParameters="Resource0 50200"/>
	</ProcessingChain>

	<LaBoGridMiddleware>
		<Stabilizer timeout="5000"/>
		<LoadBalancing buildPowerModel="false" />
		<FaultTolerance replicationEnabled="false" backupRate="100"
			chunkSize="524288" compressFiles="raw" neighborsCount="1" />
	</LaBoGridMiddleware>

</LaBoGridConfiguration>

=== cfd-learner/labogrid/src/main/bash/build-helpers/samples/conf-distributed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  LaBoGrid
  %%
  Copyright (C) 2011 LaBoGrid Team
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as
  published by the Free Software Foundation, either version 3 of the 
  License, or (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public 
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/gpl-3.0.html>.
  #L%
  -->

<LaBoGridConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="labogrid-conf-schema.xsd">

	<Experiment>
		<SimulationSequence>
			<Simulation
				iterationsCount="10" lbConfiguration="conf0"
				processingChain="proc0" startingIteration="0">
				<Input clientClass="laboGrid.ioClients.standalone.StandAloneInputClient"
					parameters="../samples/ ail3 50200" />
				<Output clientClass="laboGrid.ioClients.standalone.StandAloneOutputClient"
					parameters="524288 out/ ail3 50200" />
			</Simulation>
		</SimulationSequence>
	</Experiment>

	<LBConfiguration id="conf0">
		<Lattice class="laboGrid.lb.lattice.d3.q19.D3Q19DefaultLattice" size="(44,44,44)" />
		<Solid class="laboGrid.lb.solid.d3.D3SolidBitmap" fileId="MU44.mat.gz" type="compressed-ascii" />
		<SubLattices generatorClass="laboGrid.graphs.model.d3.D3CuboidsGenerator"
			minSubLatticesCount="4" />
	</LBConfiguration>

	<ProcessingChain id="proc0">
		<Operator class="laboGrid.procChain.operators.NonBlockingBorderSender" parameters="" />
		<Operator class="laboGrid.procChain.operators.InPlaceStream"
			parameters="" />
		<Operator class="laboGrid.procChain.operators.BorderFiller" parameters="" />
		<Operator class="laboGrid.procChain.operators.d3.q19.D3Q19PressureOperator"
			parameters="0 1.001 0.999" />
		<Operator class="laboGrid.procChain.operators.d3.q19.D3Q19MRTCollisionOperator"
			parameters="1 0 0 0 20" />
		<Operator class="laboGrid.procChain.operators.WaitBorderSent" parameters="" />
	</ProcessingChain>

	<LaBoGridMiddleware>
		<Stabilizer timeout="5000"/>
		<LoadBalancing buildPowerModel="false" />
		<FaultTolerance replicationEnabled="false" backupRate="100"
			chunkSize="524288" compressFiles="raw" neighborsCount="1" />
	</LaBoGridMiddleware>

</LaBoGridConfiguration>
